### ISSUE TITLE
Package list looks random to user

### ISSUE THREAD

**Issue by linquize** [matejc/nixui#21]
I execute the program 3 times, choosing the same channel (demo/.nix-profile).
However, each time it gives a different package list, in different order, looks random.

1st time
![1st time](https://cloud.githubusercontent.com/assets/791115/6001492/79b8939c-ab25-11e4-8f41-457020499f60.png)

2nd time
![2nd time](https://cloud.githubusercontent.com/assets/791115/6001494/7b5c086e-ab25-11e4-8cb0-efd76cde7e33.png)

3rd time
![3rd time](https://cloud.githubusercontent.com/assets/791115/6001496/7d3d5e80-ab25-11e4-839f-630bc5575e97.png)

I suggest to give a fixed list, and sort order.
The program calls `nix-env -qacP`, which gives a list in alphabetical order, and it is always the same.

**Comment by matejc** [comment]
Yeah, it is the same with config options, will do this tomorrow, I know what to do.. adjust `nedb`, preferably before filling the database with packages/config options...

**Comment by matejc** [comment]
done, it is in master
